# Intro to Pytorch

In [46]:
import collections
import hashlib
import inspect
import math
import os
import random
import re
import shutil
import sys
import tarfile
import time
import zipfile
from collections import defaultdict
import pandas as pd
import requests
from IPython import display
from matplotlib import pyplot as plt
from matplotlib_inline import backend_inline
import numpy as np
import torch
import torchvision
from PIL import Image
from scipy.spatial import distance_matrix
from torch import nn
from torch.nn import functional as F
from torchvision import transforms

In [5]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4050 Laptop GPU'

In [17]:
x = torch.arange(12, dtype=torch.float32)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
torch.Size([12])
12


In [18]:
x = x.reshape(3, 4)
print(x)
print(x.shape)
print(x.numel())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])
12


In [19]:
x = x.reshape(6, -1)
print(x)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])


In [16]:
x_zeros = torch.zeros((2, 3, 4))
print(x_zeros)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [21]:
torch.randn(3, 4)

tensor([[-0.0433,  0.6757,  0.2722,  1.0198],
        [-0.0827, -0.3377, -0.7859, -0.3738],
        [ 1.2793, -0.5049,  1.2477,  0.2523]])

In [22]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [24]:
print(x[:-1])

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [26]:
x[-1] = torch.tensor([40, 50])

In [27]:
print(x)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [40., 50.]])


In [28]:
x[:2, :] = torch.tensor(43)

In [29]:
print(x)

tensor([[43., 43.],
        [43., 43.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [40., 50.]])


In [30]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y, x - y, x * y, x / y, x**y)

tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])


In [31]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((x, y), dim = 0))
print(torch.cat((x, y), dim = 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [32]:
print(x == y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [33]:
print(x.sum())

tensor(66.)


In [35]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [36]:
print(a + b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [37]:
# Update in new memory
print(id(y))
y = y + x
print(id(y))

2258731769024
2258731776144


In [38]:
# update in place
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2258731772864
id(z): 2258731772864


In [39]:
a = z.numpy()
b = torch.from_numpy(a)
print(type(a), type(b))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [40]:
a = torch.tensor([3.5])
print(a.item())

3.5


In [43]:
print(b > x)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [45]:
z = z.reshape((2, 3, 2))
print(z)

tensor([[[ 2.,  3.],
         [ 8.,  9.],
         [ 9., 12.]],

        [[15., 18.],
         [20., 21.],
         [22., 23.]]])


# Pandas

In [59]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Tile,178100
3,NA,140000''')

In [60]:
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0     Tile  178100
3       3.0      NaN  140000


In [61]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Tile  RoofType_nan
0       NaN          False          True
1       2.0          False          True
2       4.0           True         False
3       3.0          False          True


In [62]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Tile  RoofType_nan
0       3.0          False          True
1       2.0          False          True
2       4.0           True         False
3       3.0          False          True


In [63]:
x = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
print(x)
print(y)

tensor([[3., 0., 1.],
        [2., 0., 1.],
        [4., 1., 0.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)
